# Generated by Django 3.2.8 on 2021-10-16 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 10, 16, 1, 48, 27, 819043, tzinfo=utc))),
                ('coin', models.CharField(blank=True, max_length=50, null=True)),
                ('values', models.FloatField(default=0)),
            ],
        ),
    ]
