# Generated by Django 3.2.8 on 2021-10-18 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_alter_cotacoes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacoes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 17, 46, 59, 26754, tzinfo=utc)),
        ),
    ]
